# Netlify 빌드 및 함수 설정을 위한 최종 통합 지시서

[build]
  # 기존에 사용하시던 빌드 명령을 그대로 유지합니다.
  command = "npm install"
  publish = "."

[functions]
  # ⭐️ 여기가 중요합니다! ⭐️
  # 기존 함수 폴더 경로를 그대로 사용합니다.
  # 따라서, 우리가 만든 'get-key.js' 파일도 'netlify/functions/' 폴더 안에 넣어주셔야 합니다.
  directory = "netlify/functions/"
  
  # 기존에 사용하시던 고급 설정들을 모두 유지합니다.
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

# '/api/*' 요청을 함수로 전달하는 규칙입니다. (양쪽에 모두 있었으므로 하나만 유지)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
# 기존에 사용하시던 사이트맵 리디렉션 규칙도 안전하게 유지합니다.
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200