  # Netlify 빌드 및 함수 설정을 위한 최종 지시서

[build]
  command = "npm install"
  publish = "."

[functions]
  # '비밀 요원'들이 있는 폴더의 위치를 알려줍니다.
  directory = "netlify/functions/"
  
  # '비밀 요원'들이 node.js로 만들어졌음을 알려주고,
  # 장비 목록(package.json)을 똑똑하게 처리하도록 지시합니다.
  node_bundler = "esbuild"
  
   # 이 부분이 중요합니다! 함수가 'node-fetch'를 외부 모듈로 인식하게 합니다.
  external_node_modules = ["node-fetch"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
  # 사이트맵 리디렉션 규칙을 추가합니다.
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200